#!/bin/bash


#awk '/<call_frame_dummy>/{flag=1;next}/<__do_global_ctors_aux>/{flag=0}flag' test_dump.txt > sel.txt

awk '{print $1,$2;}' $1.dump > sel2.txt

awk ' /00002800/,0' sel2.txt > sel5.txt

awk ' {if (NR!=1) {print}}' sel5.txt > sel6.txt

awk '$2 !~ /^</{print $1,$2}' sel6.txt > sel_fim.txt

awk '{print $0";"}' sel_fim.txt > sel8.txt

awk '!/^ ;/' sel8.txt > sel9.txt

awk '{print NR-1 ":" $2}' sel9.txt > sub.txt

awk 'BEGIN{print "--AUTOGENERATED RISCV32I .mif FILE FOR QUARTUS II ROM INITIALIZATION\n--caram - 01/2015\n\nWIDTH =32;\nDEPTH = 2048;\nADDRESS_RADIX = UNS;\nDATA_RADIX = HEX;\nCONTENT BEGIN\n"}{print}END{print"["NR"..2047]:00000000;\n\nEND;\n"}' sub.txt > $2

echo "END"



