+incdir+..
../cpu/memory_mapping.sv
../cache/cache_parameters.sv
../cache/cache.sv
../wsbn_ram_cache/wshbn_master_cache.sv
../work_sint2/rom.sv
../work_sint2/ram.sv
../wsbn_ram_cache/wshbn_slave_ram.sv
../cpu/riscv_div.sv
../cpu/comparator.sv
../cpu/inst_mem_ctrl.sv
../cpu/interrupt_controller.sv
../cpu/mem_ctrl.sv
../cpu/riscv_alu.sv
../cpu/riscv_cpu_no.sv
../cpu/riscv_decoder.sv
../cpu/riscv_fetch.sv
../cpu/riscv_regfile.sv
../cpu/sram_mux.sv
../riscv_wishbone.sv
../riscv_tb.sv